name: replace-github-pr-number-to-link
description: Generate a markdown link for a GitHub PR
author: GitHub Actions

inputs:
  pr-number:
    description: The PR number to generate the link for
    required: true

outputs:
  pr_link:
    description: The markdown link for the PR

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_SERVER_URL: ${{ github.server_url }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    INPUT_PR_NUMBER: ${{ inputs.pr-number }}

